@extends('layouts.front')
@section('content')
    <section class="pricing-one">
        <div class="auto-container">
            <div class="row">
                <div class="col-lg-12 pr-60 md-pr-15">
                    <div class="sec-title mb-64">
                        <h2 class="title title4 pb-30">
                            Referral
                        </h2>
                    </div>

                    <h4>How Referral Works</h4>

                    <h5>Refer Friends</h5>
                    <p>Share your referral link or QR code with your friends and social media.</p>

                    <h5>Earn Crypto!</h5>
                    <p class="margin-0 pb-30" style="text-align: justify;">Earn up to 5% commission when your friends start trading.</p>

                    <p class="margin-0 pb-30" style="text-align: justify;">Maxon has upgraded our Referral Program! Invite your friends to register and trade on maxon bots, and you and your friends can share up to 10%-5% of the referral commissions from their trading funds.</p>

                    <h4>Rules:</h4>

                    <p class="margin-0 pb-30" style="text-align: justify;">Inviters can choose to share a portion of the commissions received from the trading fees of the friends they invite, as a “kickback”. Inviters can set the sharing rates as follows:
                    </p>
                    <ul class="dots">
                        <li> If the inviter’s daily average Trading fund’s account balance is less than $10,000 and their base referral rate is 5%, they can choose to share 0%, 3% or 4% with the friends they invite.</li>
                        <li> If the inviter’s daily average trading account balance is $20,000 or more, their base referral rate is increased to 10% and they can choose to share 0%, 3%, 5%, 7% or 8% with the friends they invite.</li>
                        <li> Daily average Trading Balance Calculation Rules:here</li>
                    </ul>
                    <p class="margin-0 pb-30" style="text-align: justify;">Effective as you register and start referring.</p>
                    <ul class="">
                        <li>
                        1. Get Link
                        </li>

                        <li>2. Invite Friends</li>

                        <li>3. Earn Crypto</li>
                    </ul>
                    <h5>Details:</h5>
                    <ul class="" style="text-align: justify;">
                        <li>1. All referral commissions (both those received by inviters and those shared with their invited friends) are calculated in real-time and transferred to the respective Maxon Trading Bots accounts every time of fresh deposit.
                        </li>
                        <li>2. The settlement assets of referral commissions are the same as the commission fee generated by the actual transaction of the invited friend (invitee). If the invitee uses any cryptocurrency, the settlement assets of referral commissions and referral commissions returned are Cryptocurrency.
                        </li>
                        <li>3. Referral rates are calculated anytime of fresh deposit.
                        </li>
                        <li>4. In order for an invited friend to receive a kickback, they must register using the corresponding referral link (or QR code or referral ID). If they register using the old ID code of the person who invited them, instead of via the link, they will not receive any of the commission fee kickback offered to them by their inviter.
                        </li>
                        <li>5. There is no limit to the number of friends a single account can invite.
                        </li>

                        <li>6. If the inviter's daily average Trading balance is less than $100 their base referral rate will be reduced from 5% to 3%. At this time, the percentage allotted to the invited friend will be given priority, and his/her rate will remain unchanged. For instance, if the inviter's referral rate is reduced to 3% at this time, the invited friend will continue to maintain a normal return rate, and the inviter's referral rate will be reduced to 3%.
                        </li>
                        <li>7. Sub-accounts and margin accounts will take on the same percentage rules that apply to the spot account. For instance, the inviter will benefit from referring the invited friend’s sub-account and margin account. The invited friend’s sub-account and margin account will also enjoy the same rate he/she would get for a spot account. In the current set-up, the referral rate for the invited friend will be directly settled to the corresponding sub-account or margin account;
                        </li>
                        <li>8. Maxon Trading Bots may adjust the proportion of referrals at any point and reserves the right to adjust the rules of the referral program.
                        </li>
                    </ul>
                    <h4>Notice:</h4>

                    <p class="margin-0 pb-30" style="text-align: justify;">Maxon reserves the right to change the terms of the referral program at any time due to changing market conditions, risk of fraud, or any other factors we deem relevant.</p>
                </div>
            </div>
        </div>
    </section>
    @endsection